notes: |
  This dataset contains data obtained from the
  [HDX Humanitarian API](https://hapi.humdata.org/) (HDX HAPI),
  which provides standardized humanitarian indicators designed
  for seamless interoperability from multiple sources.
  The data facilitates automated workflows and visualizations
  to support humanitarian decision making.
  For more information, please see the HDX HAPI
  [landing page](https://data.humdata.org/hapi)
  and
  [documentation](https://hdx-hapi.readthedocs.io/en/latest/).
methodology: Registry
caveats: >
  HDX HAPI is refreshed daily, but the source datasets may have different
  update schedules. Please refer to the source datasets for each subcategory
  to verify their specific update frequency.
private: False  # has to be True or False
