datasetinfo:
  mpi_and_partial_indices:
    national:
      url: "https://ophi.org.uk/sites/default/files/2024-10/Table%201%20National%20Results%20MPI%202024.xlsx"
      sheet: "1.1 National MPI Results"
    subnational:
      url: "https://ophi.org.uk/sites/default/files/2024-10/Table%205%20Subnational%20Results%20MPI%202024.xlsx"
      sheet: "5.1 MPI Region"
  trend_over_time:
    url: "https://ophi.org.uk/sites/default/files/2024-10/Table%206%20Trends%20Over%20Time%20MPI%202024_3.xlsx"
    national_sheet: "6.1 Harmonised MPI"
    subnational_sheet: "6.4 Harmonised MPI Region"

  format: "xlsx"
  headers:
    - 5
    - 6
    - 7
    - 8
    - 9

showcaseinfo:
  # https://docs.google.com/spreadsheets/d/1mChJ1UhgLtqLD-hqbFxd5eKq-L7Nz6awD2znBcEkASs/edit?gid=0#gid=0
  urls: "https://docs.google.com/spreadsheets/d/e/2PACX-1vQPXtof5E54tGcQcDOUVwKMV9Kelkt_KqyiYCfGtSUg1B7EoMe7lfoVIHeaL2ij6fyxytplaJQojxyp/pub?gid=0&single=true&output=csv"
  notes: "The visual contains sub-national multidimensional poverty data from the country briefs published by the Oxford Poverty and Human Development Initiative (OPHI), University of Oxford."

hxltags:
  "Country ISO3": "#country+code"
  "Admin 1 PCode": "#adm1+code"
  "Admin 1 Name": "#adm1+name"
  "MPI": "#indicator+mpi"
  "Headcount Ratio": "#indicator+headcount_ratio"
  "Intensity of Deprivation": "#indicator+intensity_of_deprivation"
  "Vulnerable to Poverty": "#indicator+vulnerable_to_poverty"
  "In Severe Poverty": "#indicator+in_severe_poverty"
  "Start Date": "#date+start"
  "End Date": "#date+end"

methodology:
  text: "The global MPI is a leading policy tool that applies the multidimensional poverty methodology developed by Alkire and Foster [(2011)](https://www.sciencedirect.com/science/article/abs/pii/S0047272710001660?via%3Dihub). The global MPI is the product of incidence of poverty (H) and the average intensity of poverty (A). More information on methodology can be found here: "
  mpi_and_partial_indices: "https://ophi.org.uk/publications/MN-59"
  trend_over_time: "https://ophi.org.uk/publications/MN-60"


resource_descriptions:
  standardised_mpi: "This resource contains standardised MPI estimates by admin one unit and also shows the proportion of people who are MPI poor and experience deprivations in each of the indicators by admin one unit."
  standardised_trends: "This resource contains standardised MPI estimates and their changes over time by admin one unit and also shows the proportion of people who are MPI poor and experience deprivations in each of the indicators by admin one unit."
  mpi_national: "This table shows the MPI and its partial indices"
  mpi_subnational: "This table shows the MPI and its partial indices disaggregated by subnational regions"
  trends: "This table shows global mpi harmonized level estimates and their changes over time"
