datasetinfo:
  mpi_and_partial_indices:
    national:
      url: "https://ophi.org.uk/sites/default/files/2024-10/Table%201%20National%20Results%20MPI%202024.xlsx"
      sheet: "1.1 National MPI Results"
    subnational:
      url: "https://ophi.org.uk/sites/default/files/2024-10/Table%205%20Subnational%20Results%20MPI%202024.xlsx"
      sheet: "5.1 MPI Region"
  trend_over_time:
    url: "https://ophi.org.uk/sites/default/files/2024-10/Table%206%20Trends%20Over%20Time%20MPI%202024_3.xlsx"
    national_sheet: "6.1 Harmonised MPI"
    subnational_sheet: "6.4 Harmonised MPI Region"

  format: "xlsx"
  headers:
    - 5
    - 6
    - 7
    - 8
    - 9

showcaseinfo:
  # https://docs.google.com/spreadsheets/d/1mChJ1UhgLtqLD-hqbFxd5eKq-L7Nz6awD2znBcEkASs/edit?gid=0#gid=0
  urls: "https://docs.google.com/spreadsheets/d/e/2PACX-1vQPXtof5E54tGcQcDOUVwKMV9Kelkt_KqyiYCfGtSUg1B7EoMe7lfoVIHeaL2ij6fyxytplaJQojxyp/pub?gid=0&single=true&output=csv"
  notes: "The visual contains sub-national multidimensional poverty data from the country briefs published by the Oxford Poverty and Human Development Initiative (OPHI), University of Oxford."

hxltags:
  "Country ISO3": "#country+code"
  "Admin 1 PCode": "#adm1+code"
  "Admin 1 Name": "#adm1+name"
  "MPI": "#indicator+mpi"
  "Headcount Ratio": "#indicator+headcount_ratio"
  "Intensity of Deprivation": "#indicator+intensity_of_deprivation"
  "Vulnerable to Poverty": "#indicator+vulnerable_to_poverty"
  "In Severe Poverty": "#indicator+in_severe_poverty"
  "Survey": "#meta+survey"
  "Start Date": "#date+start"
  "End Date": "#date+end"

resource_descriptions:
  standardised_mpi: "This resource contains standardised MPI estimates by first-level administrative unit (e.g. state, province) and also shows the proportion of people who are MPI poor and experience deprivations in each of the indicators by admin one unit."
  standardised_trends: "This resource contains standardised MPI estimates and their changes over time by first-level administrative unit (e.g. state, province) and also shows the proportion of people who are MPI poor and experience deprivations in each of the indicators by admin one unit."
  mpi_national: "This table shows the MPI and its partial indices"
  mpi_subnational: "This table shows the MPI and its partial indices disaggregated by subnational regions"
  trends: "This table shows global mpi harmonized level estimates and their changes over time"

hapi_dataset:
  name: "hdx-hapi-poverty-rate"
  title: "HDX HAPI - Food Security, Nutrition & Poverty: Poverty Rate"
  tags:
    - "education"
    - "health"
    - "hxl"
    - "indicators"
    - "poverty"
  dataset_source: "Oxford Poverty & Human Development Initiative"
  license_id: "other-pd-nr"
  resource:
    name: "Global Food Security, Nutrition & Poverty: Poverty Rate"
    description: "Poverty Rate data from HDX HAPI, please see [the documentation](https://hdx-hapi.readthedocs.io/en/latest/data_usage_guides/food_security_nutrition_and_poverty/#poverty-rate) for more information"
    filename: "hdx_hapi_poverty_rate_global"
    headers:
      - "location_code"
      - "has_hrp"
      - "in_gho"
      - "provider_admin1_name"
      - "admin1_code"
      - "admin1_name"
      - "admin_level"
      - "mpi"
      - "headcount_ratio"
      - "intensity_of_deprivation"
      - "vulnerable_to_poverty"
      - "in_severe_poverty"
      - "reference_period_start"
      - "reference_period_end"
      - "dataset_hdx_id"
      - "resource_hdx_id"
